# Generated by Django 5.2 on 2025-08-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_category_cart_name_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
