# Generated by Django 5.2 on 2025-08-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_number',
        ),
        migrations.AddField(
            model_name='create_order',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
