name: Sync Branches

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Set up GitHub credentials
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Sync branches
        run: |
          TARGET_BRANCHES=("Abdulrahman" "Zeyad" "Shimaa" "Hamada" "Yara")

          for branch in "${TARGET_BRANCHES[@]}"
          do
            echo "🔁 Syncing $branch"
            git checkout $branch || git checkout -b $branch origin/$branch
            git merge origin/main --allow-unrelated-histories --no-edit || echo "❗ Merge conflict in $branch"
            git push origin $branch || echo "⚠️ Failed to push $branch"
          done
