name: Sync Branches via PR

on:
  push:
    branches:
      - main

jobs:
  sync-branches-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Create PRs to sync branches
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Sync branch with main'
          branch: 'sync/update-${{ github.ref_name }}'  # will override below in loop
          title: 'Sync with main branch'
          body: |
            Automated PR to sync this branch with main.
          labels: sync, automated

      - name: Sync branches with PRs
        run: |
          TARGET_BRANCHES=("Abdulrahman" "Zeyad" "Shimaa" "Hamada" "Yara")

          for branch in "${TARGET_BRANCHES[@]}"
          do
            echo "🔁 Creating PR to sync $branch"
            git checkout main
            git pull origin main
            git checkout -b "sync/update-$branch"
            git push --set-upstream origin "sync/update-$branch"

            gh pr create \
              --base "$branch" \
              --head "sync/update-$branch" \
              --title "Sync $branch with main" \
              --body "Automated PR to merge updates from main branch into $branch." || echo "PR creation failed or already exists"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
