# Generated by Django 5.2 on 2025-08-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('toys', 'Toys'), ('home', 'Home'), ('sports', 'Sports'), ('health', 'Health'), ('beauty', 'Beauty'), ('other', 'Other')], max_length=50),
        ),
    ]
