# Generated by Django 5.2 on 2025-08-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_quantity_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.PositiveIntegerField(default=5, help_text='Rate from 1 to 5'),
        ),
    ]
